version: '3.1'

services:
  oom-backend:
    image: oom.jfrog.io/oom/oom-backend:master
    restart: always
    environment:
      DB_URL: 'jdbc:postgresql://postgres:5432/postgres'
      DB_USER: postgres
      DB_PASSWORD: password
      SERVER_PORT: 80
    ports:
      - 3200:80
  oom-frontend:
    image: oom.jfrog.io/oom/oom-frontend:master
    restart: always
    environment:
      BACKEND_HOST: 'oom-backend'
      BACKEND_PORT: 80
    ports:
      - 80:80