version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: Justin_Gottfried@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 80:80